language: php
dist: xenial

php:
  - 7.3

services:
  - mysql

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

branches:
  only:
    - master
    - improve/thunder-testing

env:
  matrix:
    - DRUPAL_TRAVIS_PROJECT_BASEDIR=${TRAVIS_BUILD_DIR}/vendor/drupal/paragraphs_features
    - DRUPAL_TRAVIS_PROJECT_BASEDIR=${TRAVIS_BUILD_DIR}/vendor/drupal/scheduler_content_moderation_integration DRUPAL_TRAVIS_TEST_JAVASCRIPT=false
  global:
    - PATH="$TRAVIS_BUILD_DIR/bin:$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - DRUPAL_TRAVIS_PHPCS_IGNORE_PATTERN="*.md"

before_install:
  - composer config repositories.drupal composer https://packages.drupal.org/8
  - composer config repositories.assets composer https://asset-packagist.org
  - composer config repositories.paragraph_features git https://github.com/thunder/paragraphs_features.git
  - composer config repositories.scheduler_content_moderation_integration git https://github.com/thunder/scheduler_content_moderation_integration.git
  - composer require drupal/paragraphs_features:dev-8.x-1.x --no-update
  - composer require drupal/scheduler_content_moderation_integration:dev-8.x-1.x --no-update

install:
  - composer install

script:
  - test-drupal-project

notifications:
  email: false
