language: php
sudo: required

cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"
  - "$HOME/.npm"

php:
  - 7.2

branches:
  only:
    - master

env:
  matrix:
    - DRUPAL_TRAVIS_PROJECT_BASEDIR=${TRAVIS_BUILD_DIR}/vendor/drupal/paragraphs_features
    - DRUPAL_TRAVIS_PROJECT_BASEDIR=${TRAVIS_BUILD_DIR}/vendor/drupal/custom_list
    - DRUPAL_TRAVIS_PROJECT_BASEDIR=${TRAVIS_BUILD_DIR}/vendor/drupal/select2
  global:
    - PATH="${TRAVIS_BUILD_DIR}/bin:${TRAVIS_BUILD_DIR}/vendor/bin:$PATH"

before_install:
  - composer config repositories.drupal composer https://packages.drupal.org/8
  - composer config repositories.assets composer https://asset-packagist.org
  - composer config repositories.select2 git https://github.com/thunder/select2.git
  - composer config repositories.paragraph_features git https://github.com/thunder/paragraphs_features.git
  - composer config repositories.custom_list git https://github.com/thunder/custom_list.git
  - composer require drupal/paragraphs_features:dev-8.x-1.x --no-update
  - composer require drupal/custom_list:dev-8.x-1.x --no-update
  - composer require drupal/select2:dev-8.x-1.x --no-update

install:
  - composer install
  - test-drupal-module prepare_build
  - if [[ ${DRUPAL_TRAVIS_PROJECT_BASEDIR} == ${TRAVIS_BUILD_DIR}/vendor/drupal/select2 ]]; then composer require npm-asset/select2:~4.0 --no-update --working-dir=/tmp/test/select2/install2 ; fi

script:
  - test-drupal-module

notifications:
  email: false
